# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: 'true'
  branches:
    include:
    - develop
    - main
    - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '9.x'

- task: DotNetCoreCLI@2
  displayName: 'Build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: FreeEnterprise.Api/FreeEnterprise.Api.csproj
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet run --project ./FreeEnterprise.Api.UnitTests/FreeEnterprise.Api.UnitTests.csproj -c Release --report-trx --results-directory . --report-trx-filename results.trx
  displayName: 'Run tests'
  continueOnError: false

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: 'results.trx'
    searchFolder: '.'
    failTaskOnFailedTests: true
    failTaskOnMissingResultsFile: true
