# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  fe_info_api:
    build:
      context: .
      target: final
    environment:
      FE_PGHOST: fe_info_db
      FE_PGDATABASE: freeenterprise
      FE_PGUSER: fe_user
      FE_PGPASS: dev_test
      FE_PGPORT: "5432"
      Api-Key: "test"
    ports:
      - 8085:8080
    depends_on:
      fe_info_db:
        condition: service_healthy

  fe_info_db:
    build:
      context: ./free_enterprise_db/
    image: fe_api_db
    container_name: fe_api_db
    environment:
      POSTGRES_USER: fe_user
      POSTGRES_PASSWORD: dev_test
      POSTGRES_DB: freeenterprise
    volumes:
      - fe_db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "fe_user", "-d", "freeenterprise" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  fe_db_data:
